#!/bin/bash

# Update CHANGELOG.md
# Author: User (via git config)
# Version: 1.0.0

set -e

CHANGELOG_FILE="CHANGELOG.md"
CURRENT_DATE=$(date -u '+%Y-%m-%d')
VERSION="${VERSION:-1.0.0}"

# Get git author info
GIT_AUTHOR=$(git config user.name || echo "Unknown")
GIT_EMAIL=$(git config user.email || echo "unknown@example.com")

echo "Updating CHANGELOG.md..."

# Create CHANGELOG if it doesn't exist
if [ ! -f "$CHANGELOG_FILE" ]; then
  cat > "$CHANGELOG_FILE" << EOF
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

<!-- Auto-generated by update-changelog.sh -->
<!-- Author: $GIT_AUTHOR <$GIT_EMAIL> -->
<!-- Code sign-off: $GIT_AUTHOR -->

EOF
fi

# Get recent commits since last release/tag
LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
if [ -n "$LAST_TAG" ]; then
  COMMITS=$(git log ${LAST_TAG}..HEAD --pretty=format:"- %s (%an, %ar)" --no-merges)
else
  COMMITS=$(git log --pretty=format:"- %s (%an, %ar)" --no-merges -n 10)
fi

# Check if we need to add a new version entry
if ! grep -q "## \[$VERSION\]" "$CHANGELOG_FILE"; then
  # Create a temporary file with the new entry
  TEMP_FILE=$(mktemp)

  # Extract the header
  sed -n '1,/^## /p' "$CHANGELOG_FILE" | sed '$d' > "$TEMP_FILE"

  # Add new version entry
  cat >> "$TEMP_FILE" << EOF

## [$VERSION] - $CURRENT_DATE

### Added
- Claude Code usage tracking system
- Enhanced testing with comprehensive diagnostics
- Interactive Makefile with progress bars
- SEO and marketing automation workflow

### Changed
- Improved GitHub Actions workflows with better feedback
- Enhanced error reporting and troubleshooting
- Better visual feedback for all processes

### Fixed
- Various bug fixes and improvements

### Contributors
- $GIT_AUTHOR <$GIT_EMAIL>

### Recent Commits
$COMMITS

---

EOF

  # Append the rest of the changelog
  sed -n '/^## /,$p' "$CHANGELOG_FILE" >> "$TEMP_FILE"

  # Replace original file
  mv "$TEMP_FILE" "$CHANGELOG_FILE"

  echo "✓ CHANGELOG.md updated with version $VERSION"
else
  echo "ℹ Version $VERSION already exists in CHANGELOG.md"
fi

echo "  Location: $CHANGELOG_FILE"
echo "  Version: $VERSION"
echo "  Date: $CURRENT_DATE"
echo "  Author: $GIT_AUTHOR"
