#!/bin/bash

# Update CHANGELOG.md - Intelligent version
# Author: DevOps Team
# Version: 2.0.0
# Description: Automatically generates changelog entries from git commits

set -e

CHANGELOG_FILE="CHANGELOG.md"
CURRENT_DATE=$(date -u '+%Y-%m-%d')
VERSION="${VERSION:-Unreleased}"

# Get git author info
GIT_AUTHOR=$(git config user.name || echo "Unknown")
GIT_EMAIL=$(git config user.email || echo "unknown@example.com")

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📝 CHANGELOG.md Updater"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Version: $VERSION"
echo "Date: $CURRENT_DATE"
echo "Author: $GIT_AUTHOR"
echo ""

# Create CHANGELOG if it doesn't exist
if [ ! -f "$CHANGELOG_FILE" ]; then
  cat > "$CHANGELOG_FILE" << EOF
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

<!-- Auto-generated by update-changelog.sh v2.0.0 -->
<!-- Author: $GIT_AUTHOR <$GIT_EMAIL> -->

EOF
  echo "✓ Created new CHANGELOG.md"
fi

# Get commits since last version entry
# Look for the first version header and get commits since then
LAST_VERSION_DATE=$(grep -m 1 "^## \[" "$CHANGELOG_FILE" | grep -oP '\d{4}-\d{2}-\d{2}' || echo "")

if [ -n "$LAST_VERSION_DATE" ]; then
  # Get commits since the last changelog update
  COMMITS=$(git log --since="$LAST_VERSION_DATE" --pretty=format:"%s|||%an|||%ar" --no-merges 2>/dev/null || echo "")
else
  # Get last 20 commits if no previous version
  COMMITS=$(git log --pretty=format:"%s|||%an|||%ar" --no-merges -n 20 2>/dev/null || echo "")
fi

# If no new commits, exit
if [ -z "$COMMITS" ]; then
  echo "ℹ  No new commits to add to CHANGELOG"
  exit 0
fi

# Categorize commits
ADDED_ITEMS=""
CHANGED_ITEMS=""
FIXED_ITEMS=""
REMOVED_ITEMS=""
DEPRECATED_ITEMS=""
SECURITY_ITEMS=""
DOCS_ITEMS=""
CHORE_ITEMS=""

echo "→ Analyzing commits and categorizing changes..."

while IFS='|||' read -r commit author time; do
  [ -z "$commit" ] && continue

  # Skip automation commits
  if echo "$commit" | grep -qiE "(skip ci|auto-generated|update SEO|update Claude usage)"; then
    continue
  fi

  # Extract prefix and message
  prefix=$(echo "$commit" | grep -oP '^[a-z]+:' || echo "")
  message=$(echo "$commit" | sed 's/^[a-z]*: *//')

  # Categorize based on conventional commit type
  case "$prefix" in
    feat:)
      ADDED_ITEMS="${ADDED_ITEMS}- ${message} (@${author})\n"
      ;;
    fix:)
      FIXED_ITEMS="${FIXED_ITEMS}- ${message} (@${author})\n"
      ;;
    docs:)
      DOCS_ITEMS="${DOCS_ITEMS}- ${message} (@${author})\n"
      ;;
    style:|refactor:|perf:)
      CHANGED_ITEMS="${CHANGED_ITEMS}- ${message} (@${author})\n"
      ;;
    remove:|delete:)
      REMOVED_ITEMS="${REMOVED_ITEMS}- ${message} (@${author})\n"
      ;;
    security:|sec:)
      SECURITY_ITEMS="${SECURITY_ITEMS}- ${message} (@${author})\n"
      ;;
    chore:)
      # Only include significant chore items
      if echo "$message" | grep -qiE "(release|version|dependency|update)"; then
        CHORE_ITEMS="${CHORE_ITEMS}- ${message} (@${author})\n"
      fi
      ;;
    *)
      # No prefix - try to guess based on content
      if echo "$commit" | grep -qiE "^(add|implement|create|introduce)"; then
        ADDED_ITEMS="${ADDED_ITEMS}- ${message} (@${author})\n"
      elif echo "$commit" | grep -qiE "^(fix|resolve|correct|patch)"; then
        FIXED_ITEMS="${FIXED_ITEMS}- ${message} (@${author})\n"
      elif echo "$commit" | grep -qiE "^(update|change|modify|improve|enhance)"; then
        CHANGED_ITEMS="${CHANGED_ITEMS}- ${message} (@${author})\n"
      elif echo "$commit" | grep -qiE "^(remove|delete|drop)"; then
        REMOVED_ITEMS="${REMOVED_ITEMS}- ${message} (@${author})\n"
      else
        # Default to Changed
        CHANGED_ITEMS="${CHANGED_ITEMS}- ${commit} (@${author})\n"
      fi
      ;;
  esac
done <<< "$COMMITS"

# Count items
ADDED_COUNT=$(echo -e "$ADDED_ITEMS" | grep -c "^-" || echo 0)
CHANGED_COUNT=$(echo -e "$CHANGED_ITEMS" | grep -c "^-" || echo 0)
FIXED_COUNT=$(echo -e "$FIXED_ITEMS" | grep -c "^-" || echo 0)
REMOVED_COUNT=$(echo -e "$REMOVED_ITEMS" | grep -c "^-" || echo 0)
SECURITY_COUNT=$(echo -e "$SECURITY_ITEMS" | grep -c "^-" || echo 0)
DOCS_COUNT=$(echo -e "$DOCS_ITEMS" | grep -c "^-" || echo 0)

TOTAL_CHANGES=$((ADDED_COUNT + CHANGED_COUNT + FIXED_COUNT + REMOVED_COUNT + SECURITY_COUNT + DOCS_COUNT))

echo ""
echo "Changes categorized:"
echo "  Added:    $ADDED_COUNT"
echo "  Changed:  $CHANGED_COUNT"
echo "  Fixed:    $FIXED_COUNT"
echo "  Removed:  $REMOVED_COUNT"
echo "  Security: $SECURITY_COUNT"
echo "  Docs:     $DOCS_COUNT"
echo "  ─────────────"
echo "  Total:    $TOTAL_CHANGES"
echo ""

# Check if this version already exists
if grep -q "^## \[$VERSION\] - $CURRENT_DATE" "$CHANGELOG_FILE"; then
  echo "ℹ  Version $VERSION for $CURRENT_DATE already exists in CHANGELOG"
  exit 0
fi

# If no significant changes, skip update
if [ $TOTAL_CHANGES -eq 0 ]; then
  echo "ℹ  No significant changes to add to CHANGELOG (automation commits filtered)"
  exit 0
fi

# Create temporary file for new changelog
TEMP_FILE=$(mktemp)

# Extract header (everything before first version)
sed -n '1,/^## \[/p' "$CHANGELOG_FILE" | sed '$d' > "$TEMP_FILE"

# Add new version entry
cat >> "$TEMP_FILE" << EOF

## [$VERSION] - $CURRENT_DATE

EOF

# Add sections with content
if [ -n "$ADDED_ITEMS" ] && [ "$ADDED_COUNT" -gt 0 ]; then
  echo "### Added" >> "$TEMP_FILE"
  echo -e "$ADDED_ITEMS" >> "$TEMP_FILE"
fi

if [ -n "$CHANGED_ITEMS" ] && [ "$CHANGED_COUNT" -gt 0 ]; then
  echo "### Changed" >> "$TEMP_FILE"
  echo -e "$CHANGED_ITEMS" >> "$TEMP_FILE"
fi

if [ -n "$FIXED_ITEMS" ] && [ "$FIXED_COUNT" -gt 0 ]; then
  echo "### Fixed" >> "$TEMP_FILE"
  echo -e "$FIXED_ITEMS" >> "$TEMP_FILE"
fi

if [ -n "$REMOVED_ITEMS" ] && [ "$REMOVED_COUNT" -gt 0 ]; then
  echo "### Removed" >> "$TEMP_FILE"
  echo -e "$REMOVED_ITEMS" >> "$TEMP_FILE"
fi

if [ -n "$SECURITY_ITEMS" ] && [ "$SECURITY_COUNT" -gt 0 ]; then
  echo "### Security" >> "$TEMP_FILE"
  echo -e "$SECURITY_ITEMS" >> "$TEMP_FILE"
fi

if [ -n "$DOCS_ITEMS" ] && [ "$DOCS_COUNT" -gt 0 ]; then
  echo "### Documentation" >> "$TEMP_FILE"
  echo -e "$DOCS_ITEMS" >> "$TEMP_FILE"
fi

# Add separator
echo "---" >> "$TEMP_FILE"
echo "" >> "$TEMP_FILE"

# Append existing versions
sed -n '/^## \[/,$p' "$CHANGELOG_FILE" >> "$TEMP_FILE"

# Replace original file
mv "$TEMP_FILE" "$CHANGELOG_FILE"

echo "✓ CHANGELOG.md updated successfully!"
echo "  Version: $VERSION"
echo "  Date: $CURRENT_DATE"
echo "  Changes: $TOTAL_CHANGES items added"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
